import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/template/sidebar";
import Header from "@/components/template/header";
import HelpButton from "@/components/template/help-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Sidebar />
        <Header />
        <main className="ml-[18%] min-h-screen bg-beige">
          {children}
        </main>
        <div className="fixed bottom-8 right-10 z-40">
          <HelpButton />
        </div>
      </body>
    </html>
  );
}
